Leetcode
sfusurge/surge_website pull request #3
Opened 2021-05-11 21:00 UTC by joshpeng1999

Leetcode section on the website. Take a look at tablet view and lmk if it's okay

2021-05-15 04:55 UTC, praneershrest requested changes

2021-05-15 04:55 UTC, praneershrest commented on src/index.css
>    --font-body-heading: 600 36px Barlow;
This was a mistake on my part. Can you change  `--font-body-heading: 600 36px Barlow` to  `--font-body-heading: 600 30px Barlow`

2021-05-15 04:55 UTC, praneershrest commented on src/App.js
> +            <Leetcode />
Can you change this to the original App.js so we don't get too many merge conflicts :))

2021-05-15 04:55 UTC, praneershrest commented on src/components/LeetcodeText.js
> +import styles from '../css/LeetcodeText.module.css'
Add a media query so you can use the useMedia hook.

Import: `import useMediaQuery from "../utils/useMediaQuery`
Defining it: const `isDesktop = useMediaQuery('min-width: 600px')
Check out the other components (Note or UpcomingEvent)

2021-05-15 04:55 UTC, praneershrest commented on src/components/LeetcodeText.js
> +      <p className={styles.title}>Leetcode</p>
I think the marginBottom for styles.title is different for desktop and mobile. With the media hook, you can make conditional styling:

`style={isDesktop ? { marginBottom: '7px' } : { marginBottom: '5px' }}`

2021-05-15 04:55 UTC, praneershrest commented on src/components/LeetcodeText.js
> +      <p className={styles.bodyText}>
Conditional render: `style={isDesktop ? { lineHeight: '32px' } : { lineHeight: '16px' }}`

2021-05-15 04:55 UTC, praneershrest commented on src/css/LeetcodeText.module.css
> +  padding-left: 1%;
Don't think you need `padding-left: 1%`

2021-05-15 04:55 UTC, praneershrest commented on src/css/LeetcodeText.module.css
> +  padding-left: 1%;
Don't think you need padding-left: 1% and can remove margin-bottom if you conditionally render through the js component.

2021-05-15 04:55 UTC, praneershrest commented on src/css/LeetcodeText.module.css
> +  font: var(--font-body-title);
Should be `font: var(--font-body-heading)`

2021-05-15 04:55 UTC, praneershrest commented on src/css/LeetcodeText.module.css
> +  width: 94%;
Make width: 100% but I think you don't need it if you make it 100%.

2021-05-16 02:31 UTC, alikhamesy commented on src/components/Leetcode.js
> +    <div>
Unstyled divs can be replaced with `<></>` fragments

2021-06-29 23:04 UTC, praneershrest approved these changes

2021-07-24 22:20 UTC, merged